{
 "title": "Suricata Stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  (LEAD(bytes) OVER(ORDER BY time) - bytes) / (LEAD(time) OVER(ORDER BY time) - time) as \"Bandwidth\"\nFROM (\n  SELECT \n    timestamp / 1000000 as time,\n    (extra_data#>>'{decoder,bytes}')::bigint as bytes\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rules" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data#>>'{detect,engines,0,rules_loaded}')::bigint as \"Rules Loaded\",\n  (extra_data#>>'{detect,engines,0,rules_skipped}')::bigint as \"Rules Skipped\",\n  (extra_data#>>'{detect,engines,0,rules_failed}')::bigint as \"Rules Failed\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data#>>'{tcp,memuse}')::bigint as \"TCP\",\n  (extra_data#>>'{tcp,reassembly_memuse}')::bigint as \"TCP reassembly\",\n  (extra_data#>>'{flow,memuse}')::bigint as \"Flow\",\n  (extra_data#>>'{defrag,memuse}')::bigint as \"Defragmentation\",\n  (extra_data#>>'{http,memuse}')::bigint as \"HTTP\",\n  (extra_data#>>'{http,byterange,memuse}')::bigint as \"HTTP byterange\",\n  (extra_data#>>'{ippair,memuse}')::bigint as \"IP pair\",\n  (extra_data#>>'{host,memuse}')::bigint as \"Host\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  (LEAD(decoder_tcp) OVER(ORDER BY time) - decoder_tcp) / (LEAD(time) OVER(ORDER BY time) - time) as \"TCP\",\n  (LEAD(decoder_udp) OVER(ORDER BY time) - decoder_udp) / (LEAD(time) OVER(ORDER BY time) - time) as \"UDP\",\n  (LEAD(decoder_icmpv4) OVER(ORDER BY time) - decoder_icmpv4) / (LEAD(time) OVER(ORDER BY time) - time) as \"ICMPv4\",\n  (LEAD(decoder_icmpv6) OVER(ORDER BY time) - decoder_icmpv6) / (LEAD(time) OVER(ORDER BY time) - time) as \"ICMPv6\"\nFROM (\n  SELECT \n    timestamp / 1000000 as time,\n    (extra_data#>>'{decoder,tcp}')::bigint as decoder_tcp,\n    (extra_data#>>'{decoder,udp}')::bigint as decoder_udp,\n    (extra_data#>>'{decoder,icmpv4}')::bigint as decoder_icmpv4,\n    (extra_data#>>'{decoder,icmpv6}')::bigint as decoder_icmpv6\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data->>'uptime')::bigint as \"Uptime\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data#>>'{decoder,max_pkt_size}')::bigint as \"Maximum packet size\",\n  (extra_data#>>'{decoder,avg_pkt_size}')::bigint as \"Average packet size\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "title": "Application layer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(flow_failed_tcp) OVER(ORDER BY time) - flow_failed_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Raw / Failed TCP\",\n  GREATEST(0, (LEAD(flow_http) OVER(ORDER BY time) - flow_http) / (LEAD(time) OVER(ORDER BY time) - time)) as \"HTTP\",\n  GREATEST(0, (LEAD(flow_ftp) OVER(ORDER BY time) - flow_ftp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"FTP\",\n  GREATEST(0, (LEAD(flow_smtp) OVER(ORDER BY time) - flow_smtp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"SMTP\",\n  GREATEST(0, (LEAD(flow_tls) OVER(ORDER BY time) - flow_tls) / (LEAD(time) OVER(ORDER BY time) - time)) as \"TLS\",\n  GREATEST(0, (LEAD(flow_ssh) OVER(ORDER BY time) - flow_ssh) / (LEAD(time) OVER(ORDER BY time) - time)) as \"SSH\",\n  GREATEST(0, (LEAD(flow_imap) OVER(ORDER BY time) - flow_imap) / (LEAD(time) OVER(ORDER BY time) - time)) as \"IMAP\",\n  GREATEST(0, (LEAD(flow_smb) OVER(ORDER BY time) - flow_smb) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Samba\",\n  GREATEST(0, (LEAD(flow_dcerpc_tcp) OVER(ORDER BY time) - flow_dcerpc_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DCERPC TCP\",\n  GREATEST(0, (LEAD(flow_dns_tcp) OVER(ORDER BY time) - flow_dns_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DNS TCP\",\n  GREATEST(0, (LEAD(flow_modbus) OVER(ORDER BY time) - flow_modbus) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Modbus\",\n  GREATEST(0, (LEAD(flow_enip_tcp) OVER(ORDER BY time) - flow_enip_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"ENIP TCP\",\n  GREATEST(0, (LEAD(flow_dnp3) OVER(ORDER BY time) - flow_dnp3) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DNP3\",\n  GREATEST(0, (LEAD(flow_nfs_tcp) OVER(ORDER BY time) - flow_nfs_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"NFS TCP\",\n  GREATEST(0, (LEAD(flow_ntp) OVER(ORDER BY time) - flow_ntp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"NTP\",\n  GREATEST(0, (LEAD(flow_ftp_data) OVER(ORDER BY time) - flow_ftp_data) / (LEAD(time) OVER(ORDER BY time) - time)) as \"ftp-data\",\n  GREATEST(0, (LEAD(flow_tftp) OVER(ORDER BY time) - flow_tftp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"TFTP\",\n  GREATEST(0, (LEAD(flow_ike) OVER(ORDER BY time) - flow_ike) / (LEAD(time) OVER(ORDER BY time) - time)) as \"IKE\",\n  GREATEST(0, (LEAD(flow_krb5_tcp) OVER(ORDER BY time) - flow_krb5_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"KRB5 TCP\",\n  GREATEST(0, (LEAD(flow_quic) OVER(ORDER BY time) - flow_quic) / (LEAD(time) OVER(ORDER BY time) - time)) as \"QUIC\",\n  GREATEST(0, (LEAD(flow_dhcp) OVER(ORDER BY time) - flow_dhcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DHCP\",\n  GREATEST(0, (LEAD(flow_rfb) OVER(ORDER BY time) - flow_rfb) / (LEAD(time) OVER(ORDER BY time) - time)) as \"RFB\",\n  GREATEST(0, (LEAD(flow_mqtt) OVER(ORDER BY time) - flow_mqtt) / (LEAD(time) OVER(ORDER BY time) - time)) as \"MQTT\",\n  GREATEST(0, (LEAD(flow_pgsql) OVER(ORDER BY time) - flow_pgsql) / (LEAD(time) OVER(ORDER BY time) - time)) as \"PostgreSQL\",\n  GREATEST(0, (LEAD(flow_telnet) OVER(ORDER BY time) - flow_telnet) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Telnet\",\n  GREATEST(0, (LEAD(flow_websocket) OVER(ORDER BY time) - flow_websocket) / (LEAD(time) OVER(ORDER BY time) - time)) as \"WebSocket\",\n  GREATEST(0, (LEAD(flow_ldap_tcp) OVER(ORDER BY time) - flow_ldap_tcp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"LDAP TCP\",\n  GREATEST(0, (LEAD(flow_doh2) OVER(ORDER BY time) - flow_doh2) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DoH2\",\n  GREATEST(0, (LEAD(flow_rdp) OVER(ORDER BY time) - flow_rdp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"RDP\",\n  GREATEST(0, (LEAD(flow_http2) OVER(ORDER BY time) - flow_http2) / (LEAD(time) OVER(ORDER BY time) - time)) as \"HTTP 2\",\n  GREATEST(0, (LEAD(flow_bittorrent_dht) OVER(ORDER BY time) - flow_bittorrent_dht) / (LEAD(time) OVER(ORDER BY time) - time)) as \"BitTorrent DHT\",\n  GREATEST(0, (LEAD(flow_pop3) OVER(ORDER BY time) - flow_pop3) / (LEAD(time) OVER(ORDER BY time) - time)) as \"POP3\",\n  GREATEST(0, (LEAD(flow_mdns) OVER(ORDER BY time) - flow_mdns) / (LEAD(time) OVER(ORDER BY time) - time)) as \"mDNS\",\n  GREATEST(0, (LEAD(flow_snmp) OVER(ORDER BY time) - flow_snmp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"SNMP\",\n  GREATEST(0, (LEAD(flow_failed_udp) OVER(ORDER BY time) - flow_failed_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Raw / Failed UDP\",\n  GREATEST(0, (LEAD(flow_dcerpc_udp) OVER(ORDER BY time) - flow_dcerpc_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DCERPC UDP\",\n  GREATEST(0, (LEAD(flow_dns_udp) OVER(ORDER BY time) - flow_dns_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"DNS\",\n  GREATEST(0, (LEAD(flow_enip_udp) OVER(ORDER BY time) - flow_enip_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"ENIP UDP\",\n  GREATEST(0, (LEAD(flow_nfs_udp) OVER(ORDER BY time) - flow_nfs_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"NFS UDP\",\n  GREATEST(0, (LEAD(flow_krb5_udp) OVER(ORDER BY time) - flow_krb5_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"KRB5 UDP\",\n  GREATEST(0, (LEAD(flow_ldap_udp) OVER(ORDER BY time) - flow_ldap_udp) / (LEAD(time) OVER(ORDER BY time) - time)) as \"LDAP UDP\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{app_layer,flow,failed_tcp}')::bigint as flow_failed_tcp,\n    (extra_data#>>'{app_layer,flow,http}')::bigint as flow_http,\n    (extra_data#>>'{app_layer,flow,ftp}')::bigint as flow_ftp,\n    (extra_data#>>'{app_layer,flow,smtp}')::bigint as flow_smtp,\n    (extra_data#>>'{app_layer,flow,tls}')::bigint as flow_tls,\n    (extra_data#>>'{app_layer,flow,ssh}')::bigint as flow_ssh,\n    (extra_data#>>'{app_layer,flow,imap}')::bigint as flow_imap,\n    (extra_data#>>'{app_layer,flow,smb}')::bigint as flow_smb,\n    (extra_data#>>'{app_layer,flow,dcerpc_tcp}')::bigint as flow_dcerpc_tcp,\n    (extra_data#>>'{app_layer,flow,dns_tcp}')::bigint as flow_dns_tcp,\n    (extra_data#>>'{app_layer,flow,modbus}')::bigint as flow_modbus,\n    (extra_data#>>'{app_layer,flow,enip_tcp}')::bigint as flow_enip_tcp,\n    (extra_data#>>'{app_layer,flow,dnp3}')::bigint as flow_dnp3,\n    (extra_data#>>'{app_layer,flow,nfs_tcp}')::bigint as flow_nfs_tcp,\n    (extra_data#>>'{app_layer,flow,ntp}')::bigint as flow_ntp,\n    (extra_data#>>'{app_layer,flow,ftp-data}')::bigint as flow_ftp_data,\n    (extra_data#>>'{app_layer,flow,tftp}')::bigint as flow_tftp,\n    (extra_data#>>'{app_layer,flow,ike}')::bigint as flow_ike,\n    (extra_data#>>'{app_layer,flow,krb5_tcp}')::bigint as flow_krb5_tcp,\n    (extra_data#>>'{app_layer,flow,quic}')::bigint as flow_quic,\n    (extra_data#>>'{app_layer,flow,dhcp}')::bigint as flow_dhcp,\n    (extra_data#>>'{app_layer,flow,rfb}')::bigint as flow_rfb,\n    (extra_data#>>'{app_layer,flow,mqtt}')::bigint as flow_mqtt,\n    (extra_data#>>'{app_layer,flow,pgsql}')::bigint as flow_pgsql,\n    (extra_data#>>'{app_layer,flow,telnet}')::bigint as flow_telnet,\n    (extra_data#>>'{app_layer,flow,websocket}')::bigint as flow_websocket,\n    (extra_data#>>'{app_layer,flow,ldap_tcp}')::bigint as flow_ldap_tcp,\n    (extra_data#>>'{app_layer,flow,doh2}')::bigint as flow_doh2,\n    (extra_data#>>'{app_layer,flow,rdp}')::bigint as flow_rdp,\n    (extra_data#>>'{app_layer,flow,http2}')::bigint as flow_http2,\n    (extra_data#>>'{app_layer,flow,bittorrent-dht}')::bigint as flow_bittorrent_dht,\n    (extra_data#>>'{app_layer,flow,pop3}')::bigint as flow_pop3,\n    (extra_data#>>'{app_layer,flow,mdns}')::bigint as flow_mdns,\n    (extra_data#>>'{app_layer,flow,snmp}')::bigint as flow_snmp,\n    (extra_data#>>'{app_layer,flow,failed_udp}')::bigint as flow_failed_udp,\n    (extra_data#>>'{app_layer,flow,dcerpc_udp}')::bigint as flow_dcerpc_udp,\n    (extra_data#>>'{app_layer,flow,dns_udp}')::bigint as flow_dns_udp,\n    (extra_data#>>'{app_layer,flow,enip_udp}')::bigint as flow_enip_udp,\n    (extra_data#>>'{app_layer,flow,nfs_udp}')::bigint as flow_nfs_udp,\n    (extra_data#>>'{app_layer,flow,krb5_udp}')::bigint as flow_krb5_udp,\n    (extra_data#>>'{app_layer,flow,ldap_udp}')::bigint as flow_ldap_udp\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)\n"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(detect_alert) OVER(ORDER BY time) - detect_alert) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Alerts\",\n  GREATEST(0, (LEAD(detect_alerts_suppressed) OVER(ORDER BY time) - detect_alerts_suppressed) / (LEAD(time) OVER(ORDER BY time) - time)) as \"Alerts suppressed\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{detect,alert}')::bigint as detect_alert,\n    (extra_data#>>'{detect,alerts_suppressed}')::bigint as detect_alerts_suppressed\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "title": "TCP packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(tcp_syn) OVER(ORDER BY time) - tcp_syn) / (LEAD(time) OVER(ORDER BY time) - time)) as \"SYN\",\n  GREATEST(0, (LEAD(tcp_synack) OVER(ORDER BY time) - tcp_synack) / (LEAD(time) OVER(ORDER BY time) - time)) as \"SYNACK\",\n  GREATEST(0, (LEAD(tcp_rst) OVER(ORDER BY time) - tcp_rst) / (LEAD(time) OVER(ORDER BY time) - time)) as \"RST\",\n  GREATEST(0, (LEAD(tcp_urg) OVER(ORDER BY time) - tcp_urg) / (LEAD(time) OVER(ORDER BY time) - time)) as \"URG\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{tcp,syn}')::bigint as tcp_syn,\n    (extra_data#>>'{tcp,synack}')::bigint as tcp_synack,\n    (extra_data#>>'{tcp,rst}')::bigint as tcp_rst,\n    (extra_data#>>'{tcp,urg}')::bigint as tcp_urg\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "title": "Active flows and TCP sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data#>>'{flow,active}')::bigint as \"Active flows\",\n  (extra_data#>>'{tcp,active_sessions}')::bigint as \"TCP active sessions\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "title": "State of the flow on end",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(state_new) OVER(ORDER BY time) - state_new) / (LEAD(time) OVER(ORDER BY time) - time)) as New,\n  GREATEST(0, (LEAD(state_established) OVER(ORDER BY time) - state_established) / (LEAD(time) OVER(ORDER BY time) - time)) as Established,\n  GREATEST(0, (LEAD(state_closed) OVER(ORDER BY time) - state_closed) / (LEAD(time) OVER(ORDER BY time) - time)) as Closed\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{flow,end,state,new}')::bigint as state_new,\n    (extra_data#>>'{flow,end,state,established}')::bigint as state_established,\n    (extra_data#>>'{flow,end,state,closed}')::bigint as state_closed\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Decoder issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  timestamp / 1000000 as time,\n  (extra_data#>>'{decoder,event,afpacket,trunc_pkt}')::bigint as \"afpacket.trunc_pkt\",\n  (extra_data#>>'{decoder,event,ipv4,pkt_too_small}')::bigint as \"ipv4.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ipv4,hlen_too_small}')::bigint as \"ipv4.hlen_too_small\",\n  (extra_data#>>'{decoder,event,ipv4,iplen_smaller_than_hlen}')::bigint as \"ipv4.iplen_smaller_than_hlen\",\n  (extra_data#>>'{decoder,event,ipv4,trunc_pkt}')::bigint as \"ipv4.trunc_pkt\",\n  (extra_data#>>'{decoder,event,ipv4,opt_invalid}')::bigint as \"ipv4.opt_invalid\",\n  (extra_data#>>'{decoder,event,ipv4,opt_invalid_len}')::bigint as \"ipv4.opt_invalid_len\",\n  (extra_data#>>'{decoder,event,ipv4,opt_malformed}')::bigint as \"ipv4.opt_malformed\",\n  (extra_data#>>'{decoder,event,ipv4,opt_pad_required}')::bigint as \"ipv4.opt_pad_required\",\n  (extra_data#>>'{decoder,event,ipv4,opt_eol_required}')::bigint as \"ipv4.opt_eol_required\",\n  (extra_data#>>'{decoder,event,ipv4,opt_duplicate}')::bigint as \"ipv4.opt_duplicate\",\n  (extra_data#>>'{decoder,event,ipv4,opt_unknown}')::bigint as \"ipv4.opt_unknown\",\n  (extra_data#>>'{decoder,event,ipv4,wrong_ip_version}')::bigint as \"ipv4.wrong_ip_version\",\n  (extra_data#>>'{decoder,event,ipv4,icmpv6}')::bigint as \"ipv4.icmpv6\",\n  (extra_data#>>'{decoder,event,ipv4,frag_pkt_too_large}')::bigint as \"ipv4.frag_pkt_too_large\",\n  (extra_data#>>'{decoder,event,ipv4,frag_overlap}')::bigint as \"ipv4.frag_overlap\",\n  (extra_data#>>'{decoder,event,ipv4,frag_ignored}')::bigint as \"ipv4.frag_ignored\",\n  (extra_data#>>'{decoder,event,icmpv4,pkt_too_small}')::bigint as \"icmpv4.pkt_too_small\",\n  (extra_data#>>'{decoder,event,icmpv4,unknown_type}')::bigint as \"icmpv4.unknown_type\",\n  (extra_data#>>'{decoder,event,icmpv4,unknown_code}')::bigint as \"icmpv4.unknown_code\",\n  (extra_data#>>'{decoder,event,icmpv4,ipv4_trunc_pkt}')::bigint as \"icmpv4.ipv4_trunc_pkt\",\n  (extra_data#>>'{decoder,event,icmpv4,ipv4_unknown_ver}')::bigint as \"icmpv4.ipv4_unknown_ver\",\n  (extra_data#>>'{decoder,event,icmpv6,unknown_type}')::bigint as \"icmpv6.unknown_type\",\n  (extra_data#>>'{decoder,event,icmpv6,unknown_code}')::bigint as \"icmpv6.unknown_code\",\n  (extra_data#>>'{decoder,event,icmpv6,pkt_too_small}')::bigint as \"icmpv6.pkt_too_small\",\n  (extra_data#>>'{decoder,event,icmpv6,ipv6_unknown_version}')::bigint as \"icmpv6.ipv6_unknown_version\",\n  (extra_data#>>'{decoder,event,icmpv6,ipv6_trunc_pkt}')::bigint as \"icmpv6.ipv6_trunc_pkt\",\n  (extra_data#>>'{decoder,event,icmpv6,mld_message_with_invalid_hl}')::bigint as \"icmpv6.mld_message_with_invalid_hl\",\n  (extra_data#>>'{decoder,event,icmpv6,unassigned_type}')::bigint as \"icmpv6.unassigned_type\",\n  (extra_data#>>'{decoder,event,icmpv6,experimentation_type}')::bigint as \"icmpv6.experimentation_type\",\n  (extra_data#>>'{decoder,event,ipv6,pkt_too_small}')::bigint as \"ipv6.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ipv6,trunc_pkt}')::bigint as \"ipv6.trunc_pkt\",\n  (extra_data#>>'{decoder,event,ipv6,trunc_exthdr}')::bigint as \"ipv6.trunc_exthdr\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_fh}')::bigint as \"ipv6.exthdr_dupl_fh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_useless_fh}')::bigint as \"ipv6.exthdr_useless_fh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_rh}')::bigint as \"ipv6.exthdr_dupl_rh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_hh}')::bigint as \"ipv6.exthdr_dupl_hh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_dh}')::bigint as \"ipv6.exthdr_dupl_dh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_ah}')::bigint as \"ipv6.exthdr_dupl_ah\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_dupl_eh}')::bigint as \"ipv6.exthdr_dupl_eh\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_invalid_optlen}')::bigint as \"ipv6.exthdr_invalid_optlen\",\n  (extra_data#>>'{decoder,event,ipv6,wrong_ip_version}')::bigint as \"ipv6.wrong_ip_version\",\n  (extra_data#>>'{decoder,event,ipv6,exthdr_ah_res_not_null}')::bigint as \"ipv6.exthdr_ah_res_not_null\",\n  (extra_data#>>'{decoder,event,ipv6,hopopts_unknown_opt}')::bigint as \"ipv6.hopopts_unknown_opt\",\n  (extra_data#>>'{decoder,event,ipv6,hopopts_only_padding}')::bigint as \"ipv6.hopopts_only_padding\",\n  (extra_data#>>'{decoder,event,ipv6,dstopts_unknown_opt}')::bigint as \"ipv6.dstopts_unknown_opt\",\n  (extra_data#>>'{decoder,event,ipv6,dstopts_only_padding}')::bigint as \"ipv6.dstopts_only_padding\",\n  (extra_data#>>'{decoder,event,ipv6,rh_type_0}')::bigint as \"ipv6.rh_type_0\",\n  (extra_data#>>'{decoder,event,ipv6,zero_len_padn}')::bigint as \"ipv6.zero_len_padn\",\n  (extra_data#>>'{decoder,event,ipv6,fh_non_zero_reserved_field}')::bigint as \"ipv6.fh_non_zero_reserved_field\",\n  (extra_data#>>'{decoder,event,ipv6,data_after_none_header}')::bigint as \"ipv6.data_after_none_header\",\n  (extra_data#>>'{decoder,event,ipv6,unknown_next_header}')::bigint as \"ipv6.unknown_next_header\",\n  (extra_data#>>'{decoder,event,ipv6,icmpv4}')::bigint as \"ipv6.icmpv4\",\n  (extra_data#>>'{decoder,event,ipv6,frag_pkt_too_large}')::bigint as \"ipv6.frag_pkt_too_large\",\n  (extra_data#>>'{decoder,event,ipv6,frag_overlap}')::bigint as \"ipv6.frag_overlap\",\n  (extra_data#>>'{decoder,event,ipv6,frag_invalid_length}')::bigint as \"ipv6.frag_invalid_length\",\n  (extra_data#>>'{decoder,event,ipv6,frag_ignored}')::bigint as \"ipv6.frag_ignored\",\n  (extra_data#>>'{decoder,event,ipv6,ipv4_in_ipv6_too_small}')::bigint as \"ipv6.ipv4_in_ipv6_too_small\",\n  (extra_data#>>'{decoder,event,ipv6,ipv4_in_ipv6_wrong_version}')::bigint as \"ipv6.ipv4_in_ipv6_wrong_version\",\n  (extra_data#>>'{decoder,event,ipv6,ipv6_in_ipv6_too_small}')::bigint as \"ipv6.ipv6_in_ipv6_too_small\",\n  (extra_data#>>'{decoder,event,ipv6,ipv6_in_ipv6_wrong_version}')::bigint as \"ipv6.ipv6_in_ipv6_wrong_version\",\n  (extra_data#>>'{decoder,event,tcp,pkt_too_small}')::bigint as \"tcp.pkt_too_small\",\n  (extra_data#>>'{decoder,event,tcp,hlen_too_small}')::bigint as \"tcp.hlen_too_small\",\n  (extra_data#>>'{decoder,event,tcp,invalid_optlen}')::bigint as \"tcp.invalid_optlen\",\n  (extra_data#>>'{decoder,event,tcp,opt_invalid_len}')::bigint as \"tcp.opt_invalid_len\",\n  (extra_data#>>'{decoder,event,tcp,opt_duplicate}')::bigint as \"tcp.opt_duplicate\",\n  (extra_data#>>'{decoder,event,udp,pkt_too_small}')::bigint as \"udp.pkt_too_small\",\n  (extra_data#>>'{decoder,event,udp,hlen_too_small}')::bigint as \"udp.hlen_too_small\",\n  (extra_data#>>'{decoder,event,udp,hlen_invalid}')::bigint as \"udp.hlen_invalid\",\n  (extra_data#>>'{decoder,event,udp,len_invalid}')::bigint as \"udp.len_invalid\",\n  (extra_data#>>'{decoder,event,sll,pkt_too_small}')::bigint as \"sll.pkt_too_small\",\n  (extra_data#>>'{decoder,event,sll2,pkt_too_small}')::bigint as \"sll2.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ethernet,pkt_too_small}')::bigint as \"ethernet.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ethernet,unknown_ethertype}')::bigint as \"ethernet.unknown_ethertype\",\n  (extra_data#>>'{decoder,event,ppp,pkt_too_small}')::bigint as \"ppp.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ppp,vju_pkt_too_small}')::bigint as \"ppp.vju_pkt_too_small\",\n  (extra_data#>>'{decoder,event,ppp,ip4_pkt_too_small}')::bigint as \"ppp.ip4_pkt_too_small\",\n  (extra_data#>>'{decoder,event,ppp,ip6_pkt_too_small}')::bigint as \"ppp.ip6_pkt_too_small\",\n  (extra_data#>>'{decoder,event,ppp,wrong_type}')::bigint as \"ppp.wrong_type\",\n  (extra_data#>>'{decoder,event,ppp,unsup_proto}')::bigint as \"ppp.unsup_proto\",\n  (extra_data#>>'{decoder,event,pppoe,pkt_too_small}')::bigint as \"pppoe.pkt_too_small\",\n  (extra_data#>>'{decoder,event,pppoe,wrong_code}')::bigint as \"pppoe.wrong_code\",\n  (extra_data#>>'{decoder,event,pppoe,malformed_tags}')::bigint as \"pppoe.malformed_tags\",\n  (extra_data#>>'{decoder,event,gre,pkt_too_small}')::bigint as \"gre.pkt_too_small\",\n  (extra_data#>>'{decoder,event,gre,wrong_version}')::bigint as \"gre.wrong_version\",\n  (extra_data#>>'{decoder,event,gre,version0_recur}')::bigint as \"gre.version0_recur\",\n  (extra_data#>>'{decoder,event,gre,version0_flags}')::bigint as \"gre.version0_flags\",\n  (extra_data#>>'{decoder,event,gre,version0_hdr_too_big}')::bigint as \"gre.version0_hdr_too_big\",\n  (extra_data#>>'{decoder,event,gre,version0_malformed_sre_hdr}')::bigint as \"gre.version0_malformed_sre_hdr\",\n  (extra_data#>>'{decoder,event,gre,version1_chksum}')::bigint as \"gre.version1_chksum\",\n  (extra_data#>>'{decoder,event,gre,version1_route}')::bigint as \"gre.version1_route\",\n  (extra_data#>>'{decoder,event,gre,version1_ssr}')::bigint as \"gre.version1_ssr\",\n  (extra_data#>>'{decoder,event,gre,version1_recur}')::bigint as \"gre.version1_recur\",\n  (extra_data#>>'{decoder,event,gre,version1_flags}')::bigint as \"gre.version1_flags\",\n  (extra_data#>>'{decoder,event,gre,version1_no_key}')::bigint as \"gre.version1_no_key\",\n  (extra_data#>>'{decoder,event,gre,version1_wrong_protocol}')::bigint as \"gre.version1_wrong_protocol\",\n  (extra_data#>>'{decoder,event,gre,version1_malformed_sre_hdr}')::bigint as \"gre.version1_malformed_sre_hdr\",\n  (extra_data#>>'{decoder,event,gre,version1_hdr_too_big}')::bigint as \"gre.version1_hdr_too_big\",\n  (extra_data#>>'{decoder,event,vlan,header_too_small}')::bigint as \"vlan.header_too_small\",\n  (extra_data#>>'{decoder,event,vlan,unknown_type}')::bigint as \"vlan.unknown_type\",\n  (extra_data#>>'{decoder,event,vlan,too_many_layers}')::bigint as \"vlan.too_many_layers\",\n  (extra_data#>>'{decoder,event,ieee8021ah,header_too_small}')::bigint as \"ieee8021ah.header_too_small\",\n  (extra_data#>>'{decoder,event,vntag,header_too_small}')::bigint as \"vntag.header_too_small\",\n  (extra_data#>>'{decoder,event,vntag,unknown_type}')::bigint as \"vntag.unknown_type\",\n  (extra_data#>>'{decoder,event,ipraw,invalid_ip_version}')::bigint as \"ipraw.invalid_ip_version\",\n  (extra_data#>>'{decoder,event,ltnull,pkt_too_small}')::bigint as \"ltnull.pkt_too_small\",\n  (extra_data#>>'{decoder,event,ltnull,unsupported_type}')::bigint as \"ltnull.unsupported_type\",\n  (extra_data#>>'{decoder,event,sctp,pkt_too_small}')::bigint as \"sctp.pkt_too_small\",\n  (extra_data#>>'{decoder,event,esp,pkt_too_small}')::bigint as \"esp.pkt_too_small\",\n  (extra_data#>>'{decoder,event,mpls,header_too_small}')::bigint as \"mpls.header_too_small\",\n  (extra_data#>>'{decoder,event,mpls,pkt_too_small}')::bigint as \"mpls.pkt_too_small\",\n  (extra_data#>>'{decoder,event,mpls,bad_label_router_alert}')::bigint as \"mpls.bad_label_router_alert\",\n  (extra_data#>>'{decoder,event,mpls,bad_label_implicit_null}')::bigint as \"mpls.bad_label_implicit_null\",\n  (extra_data#>>'{decoder,event,mpls,bad_label_reserved}')::bigint as \"mpls.bad_label_reserved\",\n  (extra_data#>>'{decoder,event,mpls,unknown_payload_type}')::bigint as \"mpls.unknown_payload_type\",\n  (extra_data#>>'{decoder,event,vxlan,unknown_payload_type}')::bigint as \"vxlan.unknown_payload_type\",\n  (extra_data#>>'{decoder,event,geneve,unknown_payload_type}')::bigint as \"geneve.unknown_payload_type\",\n  (extra_data#>>'{decoder,event,erspan,header_too_small}')::bigint as \"erspan.header_too_small\",\n  (extra_data#>>'{decoder,event,erspan,unsupported_version}')::bigint as \"erspan.unsupported_version\",\n  (extra_data#>>'{decoder,event,erspan,too_many_vlan_layers}')::bigint as \"erspan.too_many_vlan_layers\",\n  (extra_data#>>'{decoder,event,dce,pkt_too_small}')::bigint as \"dce.pkt_too_small\",\n  (extra_data#>>'{decoder,event,chdlc,pkt_too_small}')::bigint as \"chdlc.pkt_too_small\",\n  (extra_data#>>'{decoder,event,nsh,header_too_small}')::bigint as \"nsh.header_too_small\",\n  (extra_data#>>'{decoder,event,nsh,unsupported_version}')::bigint as \"nsh.unsupported_version\",\n  (extra_data#>>'{decoder,event,nsh,bad_header_length}')::bigint as \"nsh.bad_header_length\",\n  (extra_data#>>'{decoder,event,nsh,reserved_type}')::bigint as \"nsh.reserved_type\",\n  (extra_data#>>'{decoder,event,nsh,unsupported_type}')::bigint as \"nsh.unsupported_type\",\n  (extra_data#>>'{decoder,event,nsh,unknown_payload}')::bigint as \"nsh.unknown_payload\"\nFROM stats\nWHERE\n  $__unixEpochNanoFilter(timestamp * 1000)"
    }
   ]
  },
  {
   "title": "TCP issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(tcp_ssn_memcap_drop) OVER(ORDER BY time) - tcp_ssn_memcap_drop) / (LEAD(time) OVER(ORDER BY time) - time)) as \"ssn_memcap_drop\",\n  GREATEST(0, (LEAD(tcp_invalid_checksum) OVER(ORDER BY time) - tcp_invalid_checksum) / (LEAD(time) OVER(ORDER BY time) - time)) as \"invalid_checksum\",\n  GREATEST(0, (LEAD(tcp_midstream_pickups) OVER(ORDER BY time) - tcp_midstream_pickups) / (LEAD(time) OVER(ORDER BY time) - time)) as \"midstream_pickups\",\n  GREATEST(0, (LEAD(tcp_pkt_on_wrong_thread) OVER(ORDER BY time) - tcp_pkt_on_wrong_thread) / (LEAD(time) OVER(ORDER BY time) - time)) as \"pkt_on_wrong_thread\",\n  GREATEST(0, (LEAD(tcp_ack_unseen_data) OVER(ORDER BY time) - tcp_ack_unseen_data) / (LEAD(time) OVER(ORDER BY time) - time)) as \"ack_unseen_data\",\n  GREATEST(0, (LEAD(tcp_segment_memcap_drop) OVER(ORDER BY time) - tcp_segment_memcap_drop) / (LEAD(time) OVER(ORDER BY time) - time)) as \"segment_memcap_drop\",\n  GREATEST(0, (LEAD(tcp_stream_depth_reached) OVER(ORDER BY time) - tcp_stream_depth_reached) / (LEAD(time) OVER(ORDER BY time) - time)) as \"stream_depth_reached\",\n  GREATEST(0, (LEAD(tcp_reassembly_gap) OVER(ORDER BY time) - tcp_reassembly_gap) / (LEAD(time) OVER(ORDER BY time) - time)) as \"reassembly_gap\",\n  GREATEST(0, (LEAD(tcp_overlap_diff_data) OVER(ORDER BY time) - tcp_overlap_diff_data) / (LEAD(time) OVER(ORDER BY time) - time)) as \"overlap_diff_data\",\n  GREATEST(0, (LEAD(tcp_insert_data_normal_fail) OVER(ORDER BY time) - tcp_insert_data_normal_fail) / (LEAD(time) OVER(ORDER BY time) - time)) as \"insert_data_normal_fail\",\n  GREATEST(0, (LEAD(tcp_insert_data_overlap_fail) OVER(ORDER BY time) - tcp_insert_data_overlap_fail) / (LEAD(time) OVER(ORDER BY time) - time)) as \"insert_data_overlap_fail\",\n  GREATEST(0, (LEAD(tcp_urgent_oob_data) OVER(ORDER BY time) - tcp_urgent_oob_data) / (LEAD(time) OVER(ORDER BY time) - time)) as \"urgent_oob_data\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{tcp,ssn_memcap_drop}')::bigint as tcp_ssn_memcap_drop,\n    (extra_data#>>'{tcp,invalid_checksum}')::bigint as tcp_invalid_checksum,\n    (extra_data#>>'{tcp,midstream_pickups}')::bigint as tcp_midstream_pickups,\n    (extra_data#>>'{tcp,pkt_on_wrong_thread}')::bigint as tcp_pkt_on_wrong_thread,\n    (extra_data#>>'{tcp,ack_unseen_data}')::bigint as tcp_ack_unseen_data,\n    (extra_data#>>'{tcp,segment_memcap_drop}')::bigint as tcp_segment_memcap_drop,\n    (extra_data#>>'{tcp,stream_depth_reached}')::bigint as tcp_stream_depth_reached,\n    (extra_data#>>'{tcp,reassembly_gap}')::bigint as tcp_reassembly_gap,\n    (extra_data#>>'{tcp,overlap_diff_data}')::bigint as tcp_overlap_diff_data,\n    (extra_data#>>'{tcp,insert_data_normal_fail}')::bigint as tcp_insert_data_normal_fail,\n    (extra_data#>>'{tcp,insert_data_overlap_fail}')::bigint as tcp_insert_data_overlap_fail,\n    (extra_data#>>'{tcp,urgent_oob_data}')::bigint as tcp_urgent_oob_data\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)\n"
    }
   ]
  },
  {
   "title": "Detection issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(\"alert_queue_overflow\") OVER (ORDER BY time) - \"alert_queue_overflow\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"Alert queue overflow\",\n  GREATEST(0, (LEAD(\"lua_errors\") OVER (ORDER BY time) - \"lua_errors\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"LUA general errors\",\n  GREATEST(0, (LEAD(\"lua_blocked_function_errors\") OVER (ORDER BY time) - \"lua_blocked_function_errors\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"LUA blocked function errors\",\n  GREATEST(0, (LEAD(\"lua_instruction_limit_errors\") OVER (ORDER BY time) - \"lua_instruction_limit_errors\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"LUA instruction limit errors\",\n  GREATEST(0, (LEAD(\"lua_memory_limit_errors\") OVER (ORDER BY time) - \"lua_memory_limit_errors\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"LUA memory limit errors\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{detect,alert_queue_overflow}')::bigint as \"alert_queue_overflow\",\n    (extra_data#>>'{detect,lua,errors}')::bigint as \"lua_errors\",\n    (extra_data#>>'{detect,lua,blocked_function_errors}')::bigint as \"lua_blocked_function_errors\",\n    (extra_data#>>'{detect,lua,instruction_limit_errors}')::bigint as \"lua_instruction_limit_errors\",\n    (extra_data#>>'{detect,lua,memory_limit_errors}')::bigint as \"lua_memory_limit_errors\"\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "title": "Application layer issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n    time,\n    GREATEST(0, (LEAD(\"failed_tcp.gap\") OVER (ORDER BY time) - \"failed_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"failed_tcp_gap\",\n    GREATEST(0, (LEAD(\"http.gap\") OVER (ORDER BY time) - \"http.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http_gap\",\n    GREATEST(0, (LEAD(\"http.alloc\") OVER (ORDER BY time) - \"http.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http_alloc\",\n    GREATEST(0, (LEAD(\"http.parser\") OVER (ORDER BY time) - \"http.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http_parser\",\n    GREATEST(0, (LEAD(\"http.internal\") OVER (ORDER BY time) - \"http.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http_internal\",\n    GREATEST(0, (LEAD(\"ftp.gap\") OVER (ORDER BY time) - \"ftp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ftp_gap\",\n    GREATEST(0, (LEAD(\"ftp.alloc\") OVER (ORDER BY time) - \"ftp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ftp_alloc\",\n    GREATEST(0, (LEAD(\"ftp.parser\") OVER (ORDER BY time) - \"ftp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ftp_parser\",\n    GREATEST(0, (LEAD(\"ftp.internal\") OVER (ORDER BY time) - \"ftp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ftp_internal\",\n    GREATEST(0, (LEAD(\"smtp.gap\") OVER (ORDER BY time) - \"smtp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smtp_gap\",\n    GREATEST(0, (LEAD(\"smtp.alloc\") OVER (ORDER BY time) - \"smtp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smtp_alloc\",\n    GREATEST(0, (LEAD(\"smtp.parser\") OVER (ORDER BY time) - \"smtp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smtp_parser\",\n    GREATEST(0, (LEAD(\"smtp.internal\") OVER (ORDER BY time) - \"smtp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smtp_internal\",\n    GREATEST(0, (LEAD(\"tls.gap\") OVER (ORDER BY time) - \"tls.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tls_gap\",\n    GREATEST(0, (LEAD(\"tls.alloc\") OVER (ORDER BY time) - \"tls.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tls_alloc\",\n    GREATEST(0, (LEAD(\"tls.parser\") OVER (ORDER BY time) - \"tls.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tls_parser\",\n    GREATEST(0, (LEAD(\"tls.internal\") OVER (ORDER BY time) - \"tls.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tls_internal\",\n    GREATEST(0, (LEAD(\"ssh.gap\") OVER (ORDER BY time) - \"ssh.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ssh_gap\",\n    GREATEST(0, (LEAD(\"ssh.alloc\") OVER (ORDER BY time) - \"ssh.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ssh_alloc\",\n    GREATEST(0, (LEAD(\"ssh.parser\") OVER (ORDER BY time) - \"ssh.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ssh_parser\",\n    GREATEST(0, (LEAD(\"ssh.internal\") OVER (ORDER BY time) - \"ssh.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ssh_internal\",\n    GREATEST(0, (LEAD(\"imap.gap\") OVER (ORDER BY time) - \"imap.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"imap_gap\",\n    GREATEST(0, (LEAD(\"imap.alloc\") OVER (ORDER BY time) - \"imap.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"imap_alloc\",\n    GREATEST(0, (LEAD(\"imap.parser\") OVER (ORDER BY time) - \"imap.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"imap_parser\",\n    GREATEST(0, (LEAD(\"imap.internal\") OVER (ORDER BY time) - \"imap.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"imap_internal\",\n    GREATEST(0, (LEAD(\"smb.gap\") OVER (ORDER BY time) - \"smb.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smb_gap\",\n    GREATEST(0, (LEAD(\"smb.alloc\") OVER (ORDER BY time) - \"smb.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smb_alloc\",\n    GREATEST(0, (LEAD(\"smb.parser\") OVER (ORDER BY time) - \"smb.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smb_parser\",\n    GREATEST(0, (LEAD(\"smb.internal\") OVER (ORDER BY time) - \"smb.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"smb_internal\",\n    GREATEST(0, (LEAD(\"dcerpc_tcp.gap\") OVER (ORDER BY time) - \"dcerpc_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_tcp_gap\",\n    GREATEST(0, (LEAD(\"dcerpc_tcp.alloc\") OVER (ORDER BY time) - \"dcerpc_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_tcp_alloc\",\n    GREATEST(0, (LEAD(\"dcerpc_tcp.parser\") OVER (ORDER BY time) - \"dcerpc_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_tcp_parser\",\n    GREATEST(0, (LEAD(\"dcerpc_tcp.internal\") OVER (ORDER BY time) - \"dcerpc_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_tcp_internal\",\n    GREATEST(0, (LEAD(\"dns_tcp.gap\") OVER (ORDER BY time) - \"dns_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_tcp_gap\",\n    GREATEST(0, (LEAD(\"dns_tcp.alloc\") OVER (ORDER BY time) - \"dns_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_tcp_alloc\",\n    GREATEST(0, (LEAD(\"dns_tcp.parser\") OVER (ORDER BY time) - \"dns_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_tcp_parser\",\n    GREATEST(0, (LEAD(\"dns_tcp.internal\") OVER (ORDER BY time) - \"dns_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_tcp_internal\",\n    GREATEST(0, (LEAD(\"modbus.gap\") OVER (ORDER BY time) - \"modbus.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"modbus_gap\",\n    GREATEST(0, (LEAD(\"modbus.alloc\") OVER (ORDER BY time) - \"modbus.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"modbus_alloc\",\n    GREATEST(0, (LEAD(\"modbus.parser\") OVER (ORDER BY time) - \"modbus.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"modbus_parser\",\n    GREATEST(0, (LEAD(\"modbus.internal\") OVER (ORDER BY time) - \"modbus.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"modbus_internal\",\n    GREATEST(0, (LEAD(\"enip_tcp.gap\") OVER (ORDER BY time) - \"enip_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_tcp_gap\",\n    GREATEST(0, (LEAD(\"enip_tcp.alloc\") OVER (ORDER BY time) - \"enip_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_tcp_alloc\",\n    GREATEST(0, (LEAD(\"enip_tcp.parser\") OVER (ORDER BY time) - \"enip_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_tcp_parser\",\n    GREATEST(0, (LEAD(\"enip_tcp.internal\") OVER (ORDER BY time) - \"enip_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_tcp_internal\",\n    GREATEST(0, (LEAD(\"dnp3.gap\") OVER (ORDER BY time) - \"dnp3.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dnp3_gap\",\n    GREATEST(0, (LEAD(\"dnp3.alloc\") OVER (ORDER BY time) - \"dnp3.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dnp3_alloc\",\n    GREATEST(0, (LEAD(\"dnp3.parser\") OVER (ORDER BY time) - \"dnp3.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dnp3_parser\",\n    GREATEST(0, (LEAD(\"dnp3.internal\") OVER (ORDER BY time) - \"dnp3.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dnp3_internal\",\n    GREATEST(0, (LEAD(\"nfs_tcp.gap\") OVER (ORDER BY time) - \"nfs_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_tcp_gap\",\n    GREATEST(0, (LEAD(\"nfs_tcp.alloc\") OVER (ORDER BY time) - \"nfs_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_tcp_alloc\",\n    GREATEST(0, (LEAD(\"nfs_tcp.parser\") OVER (ORDER BY time) - \"nfs_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_tcp_parser\",\n    GREATEST(0, (LEAD(\"nfs_tcp.internal\") OVER (ORDER BY time) - \"nfs_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_tcp_internal\",\n    GREATEST(0, (LEAD(\"ntp.gap\") OVER (ORDER BY time) - \"ntp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ntp_gap\",\n    GREATEST(0, (LEAD(\"ntp.alloc\") OVER (ORDER BY time) - \"ntp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ntp_alloc\",\n    GREATEST(0, (LEAD(\"ntp.parser\") OVER (ORDER BY time) - \"ntp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ntp_parser\",\n    GREATEST(0, (LEAD(\"ntp.internal\") OVER (ORDER BY time) - \"ntp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ntp_internal\",\n    GREATEST(0, (LEAD(\"data.gap\") OVER (ORDER BY time) - \"data.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"data_gap\",\n    GREATEST(0, (LEAD(\"data.alloc\") OVER (ORDER BY time) - \"data.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"data_alloc\",\n    GREATEST(0, (LEAD(\"data.parser\") OVER (ORDER BY time) - \"data.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"data_parser\",\n    GREATEST(0, (LEAD(\"data.internal\") OVER (ORDER BY time) - \"data.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"data_internal\",\n    GREATEST(0, (LEAD(\"tftp.gap\") OVER (ORDER BY time) - \"tftp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tftp_gap\",\n    GREATEST(0, (LEAD(\"tftp.alloc\") OVER (ORDER BY time) - \"tftp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tftp_alloc\",\n    GREATEST(0, (LEAD(\"tftp.parser\") OVER (ORDER BY time) - \"tftp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tftp_parser\",\n    GREATEST(0, (LEAD(\"tftp.internal\") OVER (ORDER BY time) - \"tftp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"tftp_internal\",\n    GREATEST(0, (LEAD(\"ike.gap\") OVER (ORDER BY time) - \"ike.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ike_gap\",\n    GREATEST(0, (LEAD(\"ike.alloc\") OVER (ORDER BY time) - \"ike.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ike_alloc\",\n    GREATEST(0, (LEAD(\"ike.parser\") OVER (ORDER BY time) - \"ike.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ike_parser\",\n    GREATEST(0, (LEAD(\"ike.internal\") OVER (ORDER BY time) - \"ike.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ike_internal\",\n    GREATEST(0, (LEAD(\"krb5_tcp.gap\") OVER (ORDER BY time) - \"krb5_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_tcp_gap\",\n    GREATEST(0, (LEAD(\"krb5_tcp.alloc\") OVER (ORDER BY time) - \"krb5_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_tcp_alloc\",\n    GREATEST(0, (LEAD(\"krb5_tcp.parser\") OVER (ORDER BY time) - \"krb5_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_tcp_parser\",\n    GREATEST(0, (LEAD(\"krb5_tcp.internal\") OVER (ORDER BY time) - \"krb5_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_tcp_internal\",\n    GREATEST(0, (LEAD(\"quic.gap\") OVER (ORDER BY time) - \"quic.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"quic_gap\",\n    GREATEST(0, (LEAD(\"quic.alloc\") OVER (ORDER BY time) - \"quic.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"quic_alloc\",\n    GREATEST(0, (LEAD(\"quic.parser\") OVER (ORDER BY time) - \"quic.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"quic_parser\",\n    GREATEST(0, (LEAD(\"quic.internal\") OVER (ORDER BY time) - \"quic.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"quic_internal\",\n    GREATEST(0, (LEAD(\"dhcp.gap\") OVER (ORDER BY time) - \"dhcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dhcp_gap\",\n    GREATEST(0, (LEAD(\"dhcp.alloc\") OVER (ORDER BY time) - \"dhcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dhcp_alloc\",\n    GREATEST(0, (LEAD(\"dhcp.parser\") OVER (ORDER BY time) - \"dhcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dhcp_parser\",\n    GREATEST(0, (LEAD(\"dhcp.internal\") OVER (ORDER BY time) - \"dhcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dhcp_internal\",\n    GREATEST(0, (LEAD(\"rfb.gap\") OVER (ORDER BY time) - \"rfb.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rfb_gap\",\n    GREATEST(0, (LEAD(\"rfb.alloc\") OVER (ORDER BY time) - \"rfb.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rfb_alloc\",\n    GREATEST(0, (LEAD(\"rfb.parser\") OVER (ORDER BY time) - \"rfb.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rfb_parser\",\n    GREATEST(0, (LEAD(\"rfb.internal\") OVER (ORDER BY time) - \"rfb.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rfb_internal\",\n    GREATEST(0, (LEAD(\"mqtt.gap\") OVER (ORDER BY time) - \"mqtt.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mqtt_gap\",\n    GREATEST(0, (LEAD(\"mqtt.alloc\") OVER (ORDER BY time) - \"mqtt.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mqtt_alloc\",\n    GREATEST(0, (LEAD(\"mqtt.parser\") OVER (ORDER BY time) - \"mqtt.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mqtt_parser\",\n    GREATEST(0, (LEAD(\"mqtt.internal\") OVER (ORDER BY time) - \"mqtt.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mqtt_internal\",\n    GREATEST(0, (LEAD(\"pgsql.gap\") OVER (ORDER BY time) - \"pgsql.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pgsql_gap\",\n    GREATEST(0, (LEAD(\"pgsql.alloc\") OVER (ORDER BY time) - \"pgsql.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pgsql_alloc\",\n    GREATEST(0, (LEAD(\"pgsql.parser\") OVER (ORDER BY time) - \"pgsql.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pgsql_parser\",\n    GREATEST(0, (LEAD(\"pgsql.internal\") OVER (ORDER BY time) - \"pgsql.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pgsql_internal\",\n    GREATEST(0, (LEAD(\"telnet.gap\") OVER (ORDER BY time) - \"telnet.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"telnet_gap\",\n    GREATEST(0, (LEAD(\"telnet.alloc\") OVER (ORDER BY time) - \"telnet.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"telnet_alloc\",\n    GREATEST(0, (LEAD(\"telnet.parser\") OVER (ORDER BY time) - \"telnet.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"telnet_parser\",\n    GREATEST(0, (LEAD(\"telnet.internal\") OVER (ORDER BY time) - \"telnet.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"telnet_internal\",\n    GREATEST(0, (LEAD(\"websocket.gap\") OVER (ORDER BY time) - \"websocket.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"websocket_gap\",\n    GREATEST(0, (LEAD(\"websocket.alloc\") OVER (ORDER BY time) - \"websocket.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"websocket_alloc\",\n    GREATEST(0, (LEAD(\"websocket.parser\") OVER (ORDER BY time) - \"websocket.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"websocket_parser\",\n    GREATEST(0, (LEAD(\"websocket.internal\") OVER (ORDER BY time) - \"websocket.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"websocket_internal\",\n    GREATEST(0, (LEAD(\"ldap_tcp.gap\") OVER (ORDER BY time) - \"ldap_tcp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_tcp_gap\",\n    GREATEST(0, (LEAD(\"ldap_tcp.alloc\") OVER (ORDER BY time) - \"ldap_tcp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_tcp_alloc\",\n    GREATEST(0, (LEAD(\"ldap_tcp.parser\") OVER (ORDER BY time) - \"ldap_tcp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_tcp_parser\",\n    GREATEST(0, (LEAD(\"ldap_tcp.internal\") OVER (ORDER BY time) - \"ldap_tcp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_tcp_internal\",\n    GREATEST(0, (LEAD(\"doh2.gap\") OVER (ORDER BY time) - \"doh2.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"doh2_gap\",\n    GREATEST(0, (LEAD(\"doh2.alloc\") OVER (ORDER BY time) - \"doh2.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"doh2_alloc\",\n    GREATEST(0, (LEAD(\"doh2.parser\") OVER (ORDER BY time) - \"doh2.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"doh2_parser\",\n    GREATEST(0, (LEAD(\"doh2.internal\") OVER (ORDER BY time) - \"doh2.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"doh2_internal\",\n    GREATEST(0, (LEAD(\"rdp.gap\") OVER (ORDER BY time) - \"rdp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rdp_gap\",\n    GREATEST(0, (LEAD(\"rdp.alloc\") OVER (ORDER BY time) - \"rdp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rdp_alloc\",\n    GREATEST(0, (LEAD(\"rdp.parser\") OVER (ORDER BY time) - \"rdp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rdp_parser\",\n    GREATEST(0, (LEAD(\"rdp.internal\") OVER (ORDER BY time) - \"rdp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"rdp_internal\",\n    GREATEST(0, (LEAD(\"http2.gap\") OVER (ORDER BY time) - \"http2.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http2_gap\",\n    GREATEST(0, (LEAD(\"http2.alloc\") OVER (ORDER BY time) - \"http2.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http2_alloc\",\n    GREATEST(0, (LEAD(\"http2.parser\") OVER (ORDER BY time) - \"http2.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http2_parser\",\n    GREATEST(0, (LEAD(\"http2.internal\") OVER (ORDER BY time) - \"http2.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"http2_internal\",\n    GREATEST(0, (LEAD(\"dht.gap\") OVER (ORDER BY time) - \"dht.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dht_gap\",\n    GREATEST(0, (LEAD(\"dht.alloc\") OVER (ORDER BY time) - \"dht.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dht_alloc\",\n    GREATEST(0, (LEAD(\"dht.parser\") OVER (ORDER BY time) - \"dht.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dht_parser\",\n    GREATEST(0, (LEAD(\"dht.internal\") OVER (ORDER BY time) - \"dht.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dht_internal\",\n    GREATEST(0, (LEAD(\"pop3.gap\") OVER (ORDER BY time) - \"pop3.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pop3_gap\",\n    GREATEST(0, (LEAD(\"pop3.alloc\") OVER (ORDER BY time) - \"pop3.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pop3_alloc\",\n    GREATEST(0, (LEAD(\"pop3.parser\") OVER (ORDER BY time) - \"pop3.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pop3_parser\",\n    GREATEST(0, (LEAD(\"pop3.internal\") OVER (ORDER BY time) - \"pop3.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"pop3_internal\",\n    GREATEST(0, (LEAD(\"mdns.gap\") OVER (ORDER BY time) - \"mdns.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mdns_gap\",\n    GREATEST(0, (LEAD(\"mdns.alloc\") OVER (ORDER BY time) - \"mdns.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mdns_alloc\",\n    GREATEST(0, (LEAD(\"mdns.parser\") OVER (ORDER BY time) - \"mdns.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mdns_parser\",\n    GREATEST(0, (LEAD(\"mdns.internal\") OVER (ORDER BY time) - \"mdns.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"mdns_internal\",\n    GREATEST(0, (LEAD(\"snmp.gap\") OVER (ORDER BY time) - \"snmp.gap\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"snmp_gap\",\n    GREATEST(0, (LEAD(\"snmp.alloc\") OVER (ORDER BY time) - \"snmp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"snmp_alloc\",\n    GREATEST(0, (LEAD(\"snmp.parser\") OVER (ORDER BY time) - \"snmp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"snmp_parser\",\n    GREATEST(0, (LEAD(\"snmp.internal\") OVER (ORDER BY time) - \"snmp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"snmp_internal\",\n    GREATEST(0, (LEAD(\"dcerpc_udp.alloc\") OVER (ORDER BY time) - \"dcerpc_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_udp_alloc\",\n    GREATEST(0, (LEAD(\"dcerpc_udp.parser\") OVER (ORDER BY time) - \"dcerpc_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_udp_parser\",\n    GREATEST(0, (LEAD(\"dcerpc_udp.internal\") OVER (ORDER BY time) - \"dcerpc_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dcerpc_udp_internal\",\n    GREATEST(0, (LEAD(\"dns_udp.alloc\") OVER (ORDER BY time) - \"dns_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_udp_alloc\",\n    GREATEST(0, (LEAD(\"dns_udp.parser\") OVER (ORDER BY time) - \"dns_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_udp_parser\",\n    GREATEST(0, (LEAD(\"dns_udp.internal\") OVER (ORDER BY time) - \"dns_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"dns_udp_internal\",\n    GREATEST(0, (LEAD(\"enip_udp.alloc\") OVER (ORDER BY time) - \"enip_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_udp_alloc\",\n    GREATEST(0, (LEAD(\"enip_udp.parser\") OVER (ORDER BY time) - \"enip_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_udp_parser\",\n    GREATEST(0, (LEAD(\"enip_udp.internal\") OVER (ORDER BY time) - \"enip_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"enip_udp_internal\",\n    GREATEST(0, (LEAD(\"nfs_udp.alloc\") OVER (ORDER BY time) - \"nfs_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_udp_alloc\",\n    GREATEST(0, (LEAD(\"nfs_udp.parser\") OVER (ORDER BY time) - \"nfs_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_udp_parser\",\n    GREATEST(0, (LEAD(\"nfs_udp.internal\") OVER (ORDER BY time) - \"nfs_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"nfs_udp_internal\",\n    GREATEST(0, (LEAD(\"krb5_udp.alloc\") OVER (ORDER BY time) - \"krb5_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_udp_alloc\",\n    GREATEST(0, (LEAD(\"krb5_udp.parser\") OVER (ORDER BY time) - \"krb5_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_udp_parser\",\n    GREATEST(0, (LEAD(\"krb5_udp.internal\") OVER (ORDER BY time) - \"krb5_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"krb5_udp_internal\",\n    GREATEST(0, (LEAD(\"ldap_udp.alloc\") OVER (ORDER BY time) - \"ldap_udp.alloc\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_udp_alloc\",\n    GREATEST(0, (LEAD(\"ldap_udp.parser\") OVER (ORDER BY time) - \"ldap_udp.parser\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_udp_parser\",\n    GREATEST(0, (LEAD(\"ldap_udp.internal\") OVER (ORDER BY time) - \"ldap_udp.internal\") / (LEAD(time) OVER(ORDER BY time) - time)) as \"ldap_udp_internal\"\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{app_layer,error,failed_tcp,gap}')::bigint as \"failed_tcp.gap\",\n    (extra_data#>>'{app_layer,error,http,gap}')::bigint as \"http.gap\",\n    (extra_data#>>'{app_layer,error,http,alloc}')::bigint as \"http.alloc\",\n    (extra_data#>>'{app_layer,error,http,parser}')::bigint as \"http.parser\",\n    (extra_data#>>'{app_layer,error,http,internal}')::bigint as \"http.internal\",\n    (extra_data#>>'{app_layer,error,ftp,gap}')::bigint as \"ftp.gap\",\n    (extra_data#>>'{app_layer,error,ftp,alloc}')::bigint as \"ftp.alloc\",\n    (extra_data#>>'{app_layer,error,ftp,parser}')::bigint as \"ftp.parser\",\n    (extra_data#>>'{app_layer,error,ftp,internal}')::bigint as \"ftp.internal\",\n    (extra_data#>>'{app_layer,error,smtp,gap}')::bigint as \"smtp.gap\",\n    (extra_data#>>'{app_layer,error,smtp,alloc}')::bigint as \"smtp.alloc\",\n    (extra_data#>>'{app_layer,error,smtp,parser}')::bigint as \"smtp.parser\",\n    (extra_data#>>'{app_layer,error,smtp,internal}')::bigint as \"smtp.internal\",\n    (extra_data#>>'{app_layer,error,tls,gap}')::bigint as \"tls.gap\",\n    (extra_data#>>'{app_layer,error,tls,alloc}')::bigint as \"tls.alloc\",\n    (extra_data#>>'{app_layer,error,tls,parser}')::bigint as \"tls.parser\",\n    (extra_data#>>'{app_layer,error,tls,internal}')::bigint as \"tls.internal\",\n    (extra_data#>>'{app_layer,error,ssh,gap}')::bigint as \"ssh.gap\",\n    (extra_data#>>'{app_layer,error,ssh,alloc}')::bigint as \"ssh.alloc\",\n    (extra_data#>>'{app_layer,error,ssh,parser}')::bigint as \"ssh.parser\",\n    (extra_data#>>'{app_layer,error,ssh,internal}')::bigint as \"ssh.internal\",\n    (extra_data#>>'{app_layer,error,imap,gap}')::bigint as \"imap.gap\",\n    (extra_data#>>'{app_layer,error,imap,alloc}')::bigint as \"imap.alloc\",\n    (extra_data#>>'{app_layer,error,imap,parser}')::bigint as \"imap.parser\",\n    (extra_data#>>'{app_layer,error,imap,internal}')::bigint as \"imap.internal\",\n    (extra_data#>>'{app_layer,error,smb,gap}')::bigint as \"smb.gap\",\n    (extra_data#>>'{app_layer,error,smb,alloc}')::bigint as \"smb.alloc\",\n    (extra_data#>>'{app_layer,error,smb,parser}')::bigint as \"smb.parser\",\n    (extra_data#>>'{app_layer,error,smb,internal}')::bigint as \"smb.internal\",\n    (extra_data#>>'{app_layer,error,dcerpc_tcp,gap}')::bigint as \"dcerpc_tcp.gap\",\n    (extra_data#>>'{app_layer,error,dcerpc_tcp,alloc}')::bigint as \"dcerpc_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,dcerpc_tcp,parser}')::bigint as \"dcerpc_tcp.parser\",\n    (extra_data#>>'{app_layer,error,dcerpc_tcp,internal}')::bigint as \"dcerpc_tcp.internal\",\n    (extra_data#>>'{app_layer,error,dns_tcp,gap}')::bigint as \"dns_tcp.gap\",\n    (extra_data#>>'{app_layer,error,dns_tcp,alloc}')::bigint as \"dns_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,dns_tcp,parser}')::bigint as \"dns_tcp.parser\",\n    (extra_data#>>'{app_layer,error,dns_tcp,internal}')::bigint as \"dns_tcp.internal\",\n    (extra_data#>>'{app_layer,error,modbus,gap}')::bigint as \"modbus.gap\",\n    (extra_data#>>'{app_layer,error,modbus,alloc}')::bigint as \"modbus.alloc\",\n    (extra_data#>>'{app_layer,error,modbus,parser}')::bigint as \"modbus.parser\",\n    (extra_data#>>'{app_layer,error,modbus,internal}')::bigint as \"modbus.internal\",\n    (extra_data#>>'{app_layer,error,enip_tcp,gap}')::bigint as \"enip_tcp.gap\",\n    (extra_data#>>'{app_layer,error,enip_tcp,alloc}')::bigint as \"enip_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,enip_tcp,parser}')::bigint as \"enip_tcp.parser\",\n    (extra_data#>>'{app_layer,error,enip_tcp,internal}')::bigint as \"enip_tcp.internal\",\n    (extra_data#>>'{app_layer,error,dnp3,gap}')::bigint as \"dnp3.gap\",\n    (extra_data#>>'{app_layer,error,dnp3,alloc}')::bigint as \"dnp3.alloc\",\n    (extra_data#>>'{app_layer,error,dnp3,parser}')::bigint as \"dnp3.parser\",\n    (extra_data#>>'{app_layer,error,dnp3,internal}')::bigint as \"dnp3.internal\",\n    (extra_data#>>'{app_layer,error,nfs_tcp,gap}')::bigint as \"nfs_tcp.gap\",\n    (extra_data#>>'{app_layer,error,nfs_tcp,alloc}')::bigint as \"nfs_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,nfs_tcp,parser}')::bigint as \"nfs_tcp.parser\",\n    (extra_data#>>'{app_layer,error,nfs_tcp,internal}')::bigint as \"nfs_tcp.internal\",\n    (extra_data#>>'{app_layer,error,ntp,gap}')::bigint as \"ntp.gap\",\n    (extra_data#>>'{app_layer,error,ntp,alloc}')::bigint as \"ntp.alloc\",\n    (extra_data#>>'{app_layer,error,ntp,parser}')::bigint as \"ntp.parser\",\n    (extra_data#>>'{app_layer,error,ntp,internal}')::bigint as \"ntp.internal\",\n    (extra_data#>>'{app_layer,error,ftp-data,gap}')::bigint as \"data.gap\",\n    (extra_data#>>'{app_layer,error,ftp-data,alloc}')::bigint as \"data.alloc\",\n    (extra_data#>>'{app_layer,error,ftp-data,parser}')::bigint as \"data.parser\",\n    (extra_data#>>'{app_layer,error,ftp-data,internal}')::bigint as \"data.internal\",\n    (extra_data#>>'{app_layer,error,tftp,gap}')::bigint as \"tftp.gap\",\n    (extra_data#>>'{app_layer,error,tftp,alloc}')::bigint as \"tftp.alloc\",\n    (extra_data#>>'{app_layer,error,tftp,parser}')::bigint as \"tftp.parser\",\n    (extra_data#>>'{app_layer,error,tftp,internal}')::bigint as \"tftp.internal\",\n    (extra_data#>>'{app_layer,error,ike,gap}')::bigint as \"ike.gap\",\n    (extra_data#>>'{app_layer,error,ike,alloc}')::bigint as \"ike.alloc\",\n    (extra_data#>>'{app_layer,error,ike,parser}')::bigint as \"ike.parser\",\n    (extra_data#>>'{app_layer,error,ike,internal}')::bigint as \"ike.internal\",\n    (extra_data#>>'{app_layer,error,krb5_tcp,gap}')::bigint as \"krb5_tcp.gap\",\n    (extra_data#>>'{app_layer,error,krb5_tcp,alloc}')::bigint as \"krb5_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,krb5_tcp,parser}')::bigint as \"krb5_tcp.parser\",\n    (extra_data#>>'{app_layer,error,krb5_tcp,internal}')::bigint as \"krb5_tcp.internal\",\n    (extra_data#>>'{app_layer,error,quic,gap}')::bigint as \"quic.gap\",\n    (extra_data#>>'{app_layer,error,quic,alloc}')::bigint as \"quic.alloc\",\n    (extra_data#>>'{app_layer,error,quic,parser}')::bigint as \"quic.parser\",\n    (extra_data#>>'{app_layer,error,quic,internal}')::bigint as \"quic.internal\",\n    (extra_data#>>'{app_layer,error,dhcp,gap}')::bigint as \"dhcp.gap\",\n    (extra_data#>>'{app_layer,error,dhcp,alloc}')::bigint as \"dhcp.alloc\",\n    (extra_data#>>'{app_layer,error,dhcp,parser}')::bigint as \"dhcp.parser\",\n    (extra_data#>>'{app_layer,error,dhcp,internal}')::bigint as \"dhcp.internal\",\n    (extra_data#>>'{app_layer,error,rfb,gap}')::bigint as \"rfb.gap\",\n    (extra_data#>>'{app_layer,error,rfb,alloc}')::bigint as \"rfb.alloc\",\n    (extra_data#>>'{app_layer,error,rfb,parser}')::bigint as \"rfb.parser\",\n    (extra_data#>>'{app_layer,error,rfb,internal}')::bigint as \"rfb.internal\",\n    (extra_data#>>'{app_layer,error,mqtt,gap}')::bigint as \"mqtt.gap\",\n    (extra_data#>>'{app_layer,error,mqtt,alloc}')::bigint as \"mqtt.alloc\",\n    (extra_data#>>'{app_layer,error,mqtt,parser}')::bigint as \"mqtt.parser\",\n    (extra_data#>>'{app_layer,error,mqtt,internal}')::bigint as \"mqtt.internal\",\n    (extra_data#>>'{app_layer,error,pgsql,gap}')::bigint as \"pgsql.gap\",\n    (extra_data#>>'{app_layer,error,pgsql,alloc}')::bigint as \"pgsql.alloc\",\n    (extra_data#>>'{app_layer,error,pgsql,parser}')::bigint as \"pgsql.parser\",\n    (extra_data#>>'{app_layer,error,pgsql,internal}')::bigint as \"pgsql.internal\",\n    (extra_data#>>'{app_layer,error,telnet,gap}')::bigint as \"telnet.gap\",\n    (extra_data#>>'{app_layer,error,telnet,alloc}')::bigint as \"telnet.alloc\",\n    (extra_data#>>'{app_layer,error,telnet,parser}')::bigint as \"telnet.parser\",\n    (extra_data#>>'{app_layer,error,telnet,internal}')::bigint as \"telnet.internal\",\n    (extra_data#>>'{app_layer,error,websocket,gap}')::bigint as \"websocket.gap\",\n    (extra_data#>>'{app_layer,error,websocket,alloc}')::bigint as \"websocket.alloc\",\n    (extra_data#>>'{app_layer,error,websocket,parser}')::bigint as \"websocket.parser\",\n    (extra_data#>>'{app_layer,error,websocket,internal}')::bigint as \"websocket.internal\",\n    (extra_data#>>'{app_layer,error,ldap_tcp,gap}')::bigint as \"ldap_tcp.gap\",\n    (extra_data#>>'{app_layer,error,ldap_tcp,alloc}')::bigint as \"ldap_tcp.alloc\",\n    (extra_data#>>'{app_layer,error,ldap_tcp,parser}')::bigint as \"ldap_tcp.parser\",\n    (extra_data#>>'{app_layer,error,ldap_tcp,internal}')::bigint as \"ldap_tcp.internal\",\n    (extra_data#>>'{app_layer,error,doh2,gap}')::bigint as \"doh2.gap\",\n    (extra_data#>>'{app_layer,error,doh2,alloc}')::bigint as \"doh2.alloc\",\n    (extra_data#>>'{app_layer,error,doh2,parser}')::bigint as \"doh2.parser\",\n    (extra_data#>>'{app_layer,error,doh2,internal}')::bigint as \"doh2.internal\",\n    (extra_data#>>'{app_layer,error,rdp,gap}')::bigint as \"rdp.gap\",\n    (extra_data#>>'{app_layer,error,rdp,alloc}')::bigint as \"rdp.alloc\",\n    (extra_data#>>'{app_layer,error,rdp,parser}')::bigint as \"rdp.parser\",\n    (extra_data#>>'{app_layer,error,rdp,internal}')::bigint as \"rdp.internal\",\n    (extra_data#>>'{app_layer,error,http2,gap}')::bigint as \"http2.gap\",\n    (extra_data#>>'{app_layer,error,http2,alloc}')::bigint as \"http2.alloc\",\n    (extra_data#>>'{app_layer,error,http2,parser}')::bigint as \"http2.parser\",\n    (extra_data#>>'{app_layer,error,http2,internal}')::bigint as \"http2.internal\",\n    (extra_data#>>'{app_layer,error,bittorrent-dht,gap}')::bigint as \"dht.gap\",\n    (extra_data#>>'{app_layer,error,bittorrent-dht,alloc}')::bigint as \"dht.alloc\",\n    (extra_data#>>'{app_layer,error,bittorrent-dht,parser}')::bigint as \"dht.parser\",\n    (extra_data#>>'{app_layer,error,bittorrent-dht,internal}')::bigint as \"dht.internal\",\n    (extra_data#>>'{app_layer,error,pop3,gap}')::bigint as \"pop3.gap\",\n    (extra_data#>>'{app_layer,error,pop3,alloc}')::bigint as \"pop3.alloc\",\n    (extra_data#>>'{app_layer,error,pop3,parser}')::bigint as \"pop3.parser\",\n    (extra_data#>>'{app_layer,error,pop3,internal}')::bigint as \"pop3.internal\",\n    (extra_data#>>'{app_layer,error,mdns,gap}')::bigint as \"mdns.gap\",\n    (extra_data#>>'{app_layer,error,mdns,alloc}')::bigint as \"mdns.alloc\",\n    (extra_data#>>'{app_layer,error,mdns,parser}')::bigint as \"mdns.parser\",\n    (extra_data#>>'{app_layer,error,mdns,internal}')::bigint as \"mdns.internal\",\n    (extra_data#>>'{app_layer,error,snmp,gap}')::bigint as \"snmp.gap\",\n    (extra_data#>>'{app_layer,error,snmp,alloc}')::bigint as \"snmp.alloc\",\n    (extra_data#>>'{app_layer,error,snmp,parser}')::bigint as \"snmp.parser\",\n    (extra_data#>>'{app_layer,error,snmp,internal}')::bigint as \"snmp.internal\",\n    (extra_data#>>'{app_layer,error,dcerpc_udp,alloc}')::bigint as \"dcerpc_udp.alloc\",\n    (extra_data#>>'{app_layer,error,dcerpc_udp,parser}')::bigint as \"dcerpc_udp.parser\",\n    (extra_data#>>'{app_layer,error,dcerpc_udp,internal}')::bigint as \"dcerpc_udp.internal\",\n    (extra_data#>>'{app_layer,error,dns_udp,alloc}')::bigint as \"dns_udp.alloc\",\n    (extra_data#>>'{app_layer,error,dns_udp,parser}')::bigint as \"dns_udp.parser\",\n    (extra_data#>>'{app_layer,error,dns_udp,internal}')::bigint as \"dns_udp.internal\",\n    (extra_data#>>'{app_layer,error,enip_udp,alloc}')::bigint as \"enip_udp.alloc\",\n    (extra_data#>>'{app_layer,error,enip_udp,parser}')::bigint as \"enip_udp.parser\",\n    (extra_data#>>'{app_layer,error,enip_udp,internal}')::bigint as \"enip_udp.internal\",\n    (extra_data#>>'{app_layer,error,nfs_udp,alloc}')::bigint as \"nfs_udp.alloc\",\n    (extra_data#>>'{app_layer,error,nfs_udp,parser}')::bigint as \"nfs_udp.parser\",\n    (extra_data#>>'{app_layer,error,nfs_udp,internal}')::bigint as \"nfs_udp.internal\",\n    (extra_data#>>'{app_layer,error,krb5_udp,alloc}')::bigint as \"krb5_udp.alloc\",\n    (extra_data#>>'{app_layer,error,krb5_udp,parser}')::bigint as \"krb5_udp.parser\",\n    (extra_data#>>'{app_layer,error,krb5_udp,internal}')::bigint as \"krb5_udp.internal\",\n    (extra_data#>>'{app_layer,error,ldap_udp,alloc}')::bigint as \"ldap_udp.alloc\",\n    (extra_data#>>'{app_layer,error,ldap_udp,parser}')::bigint as \"ldap_udp.parser\",\n    (extra_data#>>'{app_layer,error,ldap_udp,internal}')::bigint as \"ldap_udp.internal\"\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  { "title": "Flow engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Flow worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(wrk_spare_sync_avg) OVER(ORDER BY time) - wrk_spare_sync_avg) / (LEAD(time) OVER(ORDER BY time) - time)) as spare_sync_avg,\n  GREATEST(0, (LEAD(wrk_spare_sync) OVER(ORDER BY time) - wrk_spare_sync) / (LEAD(time) OVER(ORDER BY time) - time)) as spare_sync,\n  GREATEST(0, (LEAD(wrk_spare_sync_incomplete) OVER(ORDER BY time) - wrk_spare_sync_incomplete) / (LEAD(time) OVER(ORDER BY time) - time)) as spare_sync_incomplete,\n  GREATEST(0, (LEAD(wrk_spare_sync_empty) OVER(ORDER BY time) - wrk_spare_sync_empty) / (LEAD(time) OVER(ORDER BY time) - time)) as spare_sync_empty,\n  GREATEST(0, (LEAD(wrk_flows_evicted_needs_work) OVER(ORDER BY time) - wrk_flows_evicted_needs_work) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_evicted_needs_work,\n  GREATEST(0, (LEAD(wrk_flows_evicted_pkt_inject) OVER(ORDER BY time) - wrk_flows_evicted_pkt_inject) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_evicted_pkt_inject,\n  GREATEST(0, (LEAD(wrk_flows_evicted) OVER(ORDER BY time) - wrk_flows_evicted) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_evicted,\n  GREATEST(0, (LEAD(wrk_flows_injected) OVER(ORDER BY time) - wrk_flows_injected) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_injected,\n  GREATEST(0, (LEAD(wrk_flows_injected_max) OVER(ORDER BY time) - wrk_flows_injected_max) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_injected_max\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{flow,wrk,spare_sync_avg}')::bigint as wrk_spare_sync_avg,\n    (extra_data#>>'{flow,wrk,spare_sync}')::bigint as wrk_spare_sync,\n    (extra_data#>>'{flow,wrk,spare_sync_incomplete}')::bigint as wrk_spare_sync_incomplete,\n    (extra_data#>>'{flow,wrk,spare_sync_empty}')::bigint as wrk_spare_sync_empty,\n    (extra_data#>>'{flow,wrk,flows_evicted_needs_work}')::bigint as wrk_flows_evicted_needs_work,\n    (extra_data#>>'{flow,wrk,flows_evicted_pkt_inject}')::bigint as wrk_flows_evicted_pkt_inject,\n    (extra_data#>>'{flow,wrk,flows_evicted}')::bigint as wrk_flows_evicted,\n    (extra_data#>>'{flow,wrk,flows_injected}')::bigint as wrk_flows_injected,\n    (extra_data#>>'{flow,wrk,flows_injected_max}')::bigint as wrk_flows_injected_max\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  },
  {
   "title": "Flow manager (garbage collector)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "SELECT\n  time,\n  GREATEST(0, (LEAD(full_hash_pass) OVER(ORDER BY time) - full_hash_pass) / (LEAD(time) OVER(ORDER BY time) - time)) as full_hash_pass,\n  GREATEST(0, (LEAD(rows_per_sec) OVER(ORDER BY time) - rows_per_sec) / (LEAD(time) OVER(ORDER BY time) - time)) as rows_per_sec,\n  GREATEST(0, (LEAD(rows_maxlen) OVER(ORDER BY time) - rows_maxlen) / (LEAD(time) OVER(ORDER BY time) - time)) as rows_maxlen,\n  GREATEST(0, (LEAD(flows_checked) OVER(ORDER BY time) - flows_checked) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_checked,\n  GREATEST(0, (LEAD(flows_notimeout) OVER(ORDER BY time) - flows_notimeout) / (LEAD(time) OVER(ORDER BY time) - time)) as \"flows no timeout\",\n  GREATEST(0, (LEAD(flows_timeout) OVER(ORDER BY time) - flows_timeout) / (LEAD(time) OVER(ORDER BY time) - time)) as \"flows with timeout\",\n  GREATEST(0, (LEAD(flows_evicted) OVER(ORDER BY time) - flows_evicted) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_evicted,\n  GREATEST(0, (LEAD(flows_evicted_needs_work) OVER(ORDER BY time) - flows_evicted_needs_work) / (LEAD(time) OVER(ORDER BY time) - time)) as flows_evicted_needs_work\nFROM (\n  SELECT\n    timestamp / 1000000 as time,\n    (extra_data#>>'{flow,mgr,full_hash_pass}')::bigint as full_hash_pass,\n    (extra_data#>>'{flow,mgr,rows_per_sec}')::bigint as rows_per_sec,\n    (extra_data#>>'{flow,mgr,rows_maxlen}')::bigint as rows_maxlen,\n    (extra_data#>>'{flow,mgr,flows_checked}')::bigint as flows_checked,\n    (extra_data#>>'{flow,mgr,flows_notimeout}')::bigint as flows_notimeout,\n    (extra_data#>>'{flow,mgr,flows_timeout}')::bigint as flows_timeout,\n    (extra_data#>>'{flow,mgr,flows_evicted}')::bigint as flows_evicted,\n    (extra_data#>>'{flow,mgr,flows_evicted_needs_work}')::bigint as flows_evicted_needs_work\n  FROM stats\n  WHERE\n    $__unixEpochNanoFilter(timestamp * 1000)\n)"
    }
   ]
  }
 ]
}